- name: Copy nginx conf to server
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/sites-available/myra.conf
    owner: root
    group: root
    mode: 0644
- name: making sure nginx default site is removed
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: 
    - restart nginx
- name: Activating site
  file:
    src: /etc/nginx/sites-available/myra.conf
    dest: /etc/nginx/sites-enabled/myra.conf
    state: link    
  notify: 
    - restart nginx