---
- name: Installing system components
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 36000
    state: installed
  with_items:
    - nginx
    - git
    - python-pip 
    - python-dev 
    - libpq-dev 
- name: Installing app components
  pip:
    name: "{{item}}"
  with_items:
    - django 
    - gunicorn 
    - psycopg2