---
  - name: Create deploy dirs
    file:
      path: /var/myra/
      state: directory
      mode: 0755
  - name: Clone/pull project repo
    git: 
      repo: https://metarain.githost.io/kunal/devopsDummy.git 
      dest: /var/myra 
      accept_hostkey: yes
    notify:
    - restart gunicorn

  - name: install python packages
    pip: requirements=/var/myra/requirements.txt
    notify:
    - restart gunicorn
  - name: start application
    # django_manage: 
    #   command: runserver &
    #   app_path: /var/myra/ 
    shell: ./manage.py runserver &
    args:
      chdir: /var/myra/
    async: 10
    poll: 0
